name = "coddeys/fractional-nft-real-estate"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'coddeys/fractional-nft-real-estate'"

[repository]
user = "coddeys"
project = "fractional-nft-real-estate"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.8.0"
source = "github"
