name: Tests

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: coddeys/setup-aiken@0f28d2e4b3873eada8a88ef98dcfc076ec2a2cbe
        with:
          version: v1.0.26-alpha

      - run: aiken fmt --check
      - run: aiken check -D
      - run: aiken build
